logging:   # SpringBoot日志配置
  level:
    # ChatClient 监控日志的等级
    org.springframework.ai.chat.client.advisor: debug

spring:
  ai:
    dashscope:
      # 阿里百炼大模型服务平台 API-Key申请文档
      # https://help.aliyun.com/zh/model-studio/get-api-key
      api-key: ${DASHSCOPE_API_KEY:your-api-key-here}
      chat:
        options:
          model: deepseek-r1  # 指定DeepSeek的模型名称


